module.exports = {
    ADD_NEW_POSITION: 'ADD_NEW_POSITION',
    ADD_NEW_APPLICANT:'ADD_NEW_APPLICANT',
    ADD_NEW_APPLICANT_NO_POSITION:'ADD_NEW_APPLICANT_NO_POSITION',
    DELETED_POSITION: 'DELETED_POSITION',
}